# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Blastcraft parameters
mod_version=0.6.0-0
mod_id=blastcraft
mod_group_id=blastcraft
mod_name=Blastcraft

# Version parameters
mod_license=All Rights Reserved
mod_authors=aurilisdev
mod_credits=Thanks to all contributors. Brazil lang key by FITFC.
mod_description=The blast-resistant blocks from ICBM separated into a different mod to allow for more modular playstyles with Ballistix
