modLoader="javafml" #mandatory
loaderVersion="[47,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
issueTrackerURL="https://github.com/aurilisdev/Blastcraft" #optional
[[mods]] #mandatory
modId="blastcraft" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Blastcraft" #mandatory
displayURL="https://github.com/aurilisdev/Blastcraft" #optional
logoFile="blastcraft.png" #optional
credits="Thanks to all contributors. Brazil lang file by FITFC." #optional
authors="aurilisdev" #optional
description='''
'''
[[dependencies.blastcraft]]
    modId="electrodynamics"
    mandatory=true
    versionRange="[1.20.1-0.9,)"
    ordering="NONE"
    side="BOTH"